### PR TITLE
Fix unchecked removal of commands by app name

### LINKED ISSUE #1634: Unloading an app destroys any command with its name, regardless of ownership
Unloading an app will currently remove a command with the app's name, regardless if it's that app's command or a vanilla/mod's one.

That includes failing to load an app.

### PR DESCRIPTION
**Pull request by altrisi**
Fixes #1634.

Should this make it into a 1.19.3 release? This isn't directly on top of 1.19.3, but it doesn't include any 23w03a commits, so it could be merged into 1.19.3 without many issues by just changing the target branch. Update: Actually it's sitting on top of a commit with an NPE.

The bug is present in all 1.19.3 versions, and on the latest 1.19.2 version. Older versions are unaffected.

### CODE REVIEW

File: src/main/java/carpet/script/CarpetScriptHost.java [hunk 1]
```diff
@@ -401,7 +408,7 @@ public Boolean addAppCommands(Consumer<Component> notifier)
                 LiteralArgumentBuilder<CommandSourceStack> command = readCommands(commandValidator);
                 if (command != null)
                 {
-                    scriptServer().server.getCommands().getDispatcher().register(command);
+                	registerCommand(command);
```
Comment (altrisi) [inline src/main/java/carpet/script/CarpetScriptHost.java:411]:
```suggestion
                    registerCommand(command);
```
