### PR TITLE
Fake players can be spawned in survival mode while flying

### LINKED ISSUE #1263: [Bug][Bots] Players spawned in survival while spawning player is in spectator, spawn flying in survival
Basically the title.

## Steps to reproduce
- Run `/player Steve spawn at x y z facing u v in minecraft:overworld in survival`, y being any y level mid air, while in spectator, 

## Expectation
- Steve should fall on ground since its in survival mode

## Observation
- Steve will spawn flying midair in survival mode. If you do `/player Steve move forward` they walk forward mid air

## Version info
- Game: 1.17.1
- Carpet 1.4.56

### PR DESCRIPTION
**Pull request by Ghoulboy78**
Fixes #1263 
Basically if you're in spectator (or creative for that matter), spawning a fake player in survival or adventure mode would cause that player to have flying abilities.

### CODE REVIEW

File: src/main/java/carpet/commands/PlayerCommand.java [hunk 1]
```diff
@@ -299,6 +299,9 @@ private static int spawn(CommandContext<ServerCommandSource> context) throws Com
         {
             // Force override flying to true for spectator players, or they will fell out of the world.
             flying = true;
+        } else if(mode.isSurvivalLike()){
+            // Force override flying to true for survival-like players, or they will fly too
```
Comment (James103) [inline src/main/java/carpet/commands/PlayerCommand.java:303]:
```suggestion
            // Force override flying to false for survival-like players, or they will fly too
```

**Review by gnembon — APPROVED** [review]
