### PR TITLE
Fixing `/player botname stop` with relation to *fake* player movement

### LINKED ISSUE #1680: Can't move minecarts using movement keys
Nothing happens when hold W in a minecart. It should start moving but it doesn't. All carpet rules are disabled.

Steps to reproduce:

1. Join singleplayer world with carpet mod installed
2. Place rails and install minecart on it
3. Sit in minecart and hold W

### PR DESCRIPTION
**Pull request by Ghoulboy78**
As opposed to real player movement.
Closes #1680.
Supersedes and therefore closes #1681.

### CODE REVIEW

File: src/main/java/carpet/helpers/EntityPlayerActionPack.java [hunk 1]
```diff
@@ -238,8 +239,12 @@ public void onUpdate()
             }
         }
         float vel = sneaking?0.3F:1.0F;
-        player.zza = forward*vel;
-        player.xxa = strafing*vel;
+        if (forward != 0.0F || player instanceof EntityPlayerMPFake) {
```
Comment (altrisi) [inline src/main/java/carpet/helpers/EntityPlayerActionPack.java:242]:
```suggestion
        // The != 0.0F check are needed given else real players can't control minecarts, however it works with fakes and else they don't stop immediately
        if (forward != 0.0F || player instanceof EntityPlayerMPFake) {
```

**Review by altrisi — APPROVED** [review]
Works, no regressions
